services:
  database:
    build: ./database
    image: mathieumdg/my-database:1.0
    container_name: database
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database-backend-network
    

  backend:
    build: ./simpleapi
    image: mathieumdg/my-backend:1.0
    container_name: backend
    restart: unless-stopped
    networks:
      - backend-httpd-network
      - database-backend-network
    depends_on:
      - database

  httpd:
    build: ./httpd
    image: mathieumdg/my-httpd:1.0
    container_name: httpd
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - backend-httpd-network
    depends_on:
      - backend

networks:
  database-backend-network:
  backend-httpd-network:

volumes:
  db-data: